create database Assign_2;
USE Assign_2;
DROP TABLE PRODUCTS;
CREATE TABLE PRODUCTS(
PRODUCT_ID INT PRIMARY KEY auto_increment,
PRODUCT_NAME VARCHAR(50) NOT NULL,
CATEGORY ENUM ( 'ELECTRONICS', 'FURNITURE', 'CLOTHING', 'GROCERY' ),
PRICE DECIMAL (10,2) CHECK (PRICE>0 ),
QUANTITY INT DEFAULT 10,
SUPPLIER_NAME SET ( 'SUPPLIER1','SUPPLIER2','SUPPLIER3' ),
MANUFACTURE_DATE DATE CHECK ( MANUFACTURE_DATE<= current_date()),
EXPIRY_DATE DATE
);
INSERT INTO PRODUCTS (PRODUCT_NAME,CATEGORY,PRICE,QUANTITY,SUPPLIER_NAME,MANUFACTURE_DATE,EXPIRY_DATE) VALUES 
('SOFA','FURNITURE', 499.99, 15, 'SUPPLIER1', '2024-10-15', '2026-10-15'),
('CHAIR','FURNITURE', 599.99, 120, 'SUPPLIER2', '2024-10-15', '2026-10-15');
SELECT* FROM PRODUCTS;

