USE PRACTICE;
DELIMITER //
CREATE FUNCTION ADD_NUMBERS(A INT, B INT)
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN A+B;
END //
DELIMITER ;
SELECT ADD_NUMBERS(23,20) AS ADDITION;
DELIMITER //
CREATE FUNCTION PROD_NUMBERS(A INT,B INT)
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN A*B;
END //
DELIMITER // ;
SELECT PROD_NUMBERS(2,5) AS PRODUCT;    



-- WRITE A FUNCTION TO CONVERT FERENHEIT TO CELCIUS
DELIMITER //
CREATE FUNCTION FAR_TO_CEL(N FLOAT)
RETURNS FLOAT
DETERMINISTIC
BEGIN
	DECLARE RES FLOAT;
    SET RES=(5/9)*(N-32);
    RETURN RES;
END //
DELIMITER // ;
SELECT FAR_TO_CEL(97.8) AS CELCIUS;   

-- WRITE A FUNCTION TO GENERATE A NUMBER FROM 1 TO 10 