CREATE DATABASE FUNCTIONS;
USE FUNCTIONS;
CREATE TABLE CUSTOMERS (
CUST_ID INT PRIMARY KEY auto_increment,
CUST_NAME VARCHAR(50),
CUST_EMAIL VARCHAR(40),
CUST_REGISTRATION_DATE datetime DEFAULT NOW(),
CUST_COUNTRY VARCHAR(40)
);
INSERT INTO CUSTOMERS(CUST_NAME,CUST_EMAIL,CUST_REGISTRATION_DATE,CUST_COUNTRY) VALUES
("ANKIT","ANK@GMAIL.COM",'2024-11-10',"INDIA"),
("MONU","MON@GMAIL.COM",'2024-11-11',"INDIA"),
("RINKU","RINKU@GMAIL.COM",'2024-11-12',"INDIA"),
("AKAR","AKAR@GMAIL.COM",'2024-11-13',"INDIA"),
("KOMAL","KOMAL@GMAIL.COM",'2024-11-15',"INDIA");
INSERT INTO CUSTOMERS(CUST_NAME,CUST_EMAIL,CUST_COUNTRY) VALUES
("SUBHAM","SUBH@GMAIL.COM","INDIA");
INSERT INTO CUSTOMERS(CUST_NAME,CUST_EMAIL,CUST_COUNTRY) VALUES
("HARIOM","HARI@GMAIL.COM","INDIA");
INSERT INTO CUSTOMERS(CUST_NAME,CUST_EMAIL,CUST_COUNTRY) VALUES
("SAKET","SAKET@GMAIL.COM","INDIA");
SELECT * FROM CUSTOMERS;

CREATE TABLE PRODUCTS(
PROD_ID INT PRIMARY KEY auto_increment,
PROD_NAME VARCHAR(40),
PROD_PRICE FLOAT
);
INSERT INTO PRODUCTS (PROD_NAME,PROD_PRICE) VALUES
("TABLE",499),
("CHAIR",399),
("LAPTOP",11299),
("MOUSE",799),
("KEYBOARD",899);
SELECT * FROM PRODUCTS;

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY auto_increment,
CUSTOMER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
ORDER_DATE DATETIME DEFAULT NOW(),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUST_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PROD_ID)
);
INSERT INTO ORDERS (CUSTOMER_ID,PRODUCT_ID,QUANTITY,ORDER_DATE) VALUES
(1,1,3,NOW());
SELECT * FROM ORDERS ;
INSERT INTO ORDERS (CUSTOMER_ID,PRODUCT_ID,QUANTITY,ORDER_DATE) VALUES
(1,3,4,NOW());
INSERT INTO ORDERS (CUSTOMER_ID,PRODUCT_ID,QUANTITY,ORDER_DATE) VALUES
(5,1,1,NOW());
INSERT INTO ORDERS (CUSTOMER_ID,PRODUCT_ID,QUANTITY,ORDER_DATE) VALUES
(4,4,3,NOW());
INSERT INTO ORDERS (CUSTOMER_ID,PRODUCT_ID,QUANTITY,ORDER_DATE) VALUES
(3,5,4,NOW());
SELECT * FROM ORDERS WHERE ORDER_DATE>now()-INTERVAL 1 DAY;
SELECT * FROM ORDERS WHERE ORDER_DATE>now()-INTERVAL 7 MINUTE;
SELECT * FROM ORDERS ORDER BY ORDER_DATE DESC;
SELECT current_date();
SELECT * FROM ORDERS WHERE ORDER_DATE>now()-INTERVAL 1 MONTH;
SELECT MONTH(current_date()) FROM ORDERS;

SELECT * FROM CUSTOMERS where MONTH(CUST_REGISTRATION_DATE)=EXTRACT(MONTH FROM current_date());

select EXTRACT(MONTH FROM CURRENT_DATE()) FROM ORDERS;
SELECT * FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
ON C.CUST_ID=O.CUSTOMER_ID
INNER JOIN PRODUCTS AS P
ON C.CUST_ID=P.PROD_ID;
select EXTRACT(MONTH FROM ORDER_DATE) FROM ORDERS;