CREATE database SBIBANK;
USE SBIBANK;
DROP TABLE MAIN_TABLE;
CREATE TABLE MAIN_TABLE(
CUST_ID INT auto_increment primary KEY,
CUST_NAME VARCHAR(50),
CUST_AC_NO bigint unique,
CUST_MOB bigint unique,
CUST_BALANCE bigint,
CUST_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CUST_UPDATED_AT TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);

CREATE TABLE BACKUP_TABLE(
CUST_ID INT,
CUST_NAME VARCHAR(50),
CUST_AC_NO bigint unique,
CUST_MOB bigint unique,
CUST_BALANCE bigint,
CUST_CREATED_AT TIMESTAMP ,
CUST_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CUST_DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATING TRIGGER

DELIMITER //
CREATE TRIGGER BEFORE_MAIN_TABLE_DELETE
BEFORE DELETE ON MAIN_TABLE
FOR each row
	BEGIN
		INSERT INTO BACKUP_TABLE(CUST_ID,CUST_NAME,CUST_AC_NO,CUST_MOB,CUST_BALANCE,CUST_CREATED_AT,CUST_UPDATED_AT)
        VALUES (OLD.CUST_ID,OLD.CUST_NAME,OLD.CUST_AC_NO,OLD.CUST_MOB,OLD.CUST_BALANCE,OLD.CUST_CREATED_AT,OLD.CUST_UPDATED_AT);
    END;
    //
    DELIMITER ;
    
INSERT INTO MAIN_TABLE(CUST_NAME,CUST_AC_NO,CUST_MOB,CUST_BALANCE) VALUES
('DEV',27878737,989887896,90000);
INSERT INTO MAIN_TABLE(CUST_NAME,CUST_AC_NO,CUST_MOB,CUST_BALANCE) VALUES
('SAM',26578737,988667896,90090);
INSERT INTO MAIN_TABLE(CUST_NAME,CUST_AC_NO,CUST_MOB,CUST_BALANCE) VALUES
('RAM',26778737,984567896,70000); 

UPDATE MAIN_TABLE SET CUST_BALANCE=40000 WHERE CUST_NAME='DEV'; 
DELETE FROM MAIN_TABLE WHERE CUST_ID=4;

select* FROM MAIN_TABLE;
select* FROM BACKUP_TABLE;
